### ISSUE TITLE
formulation error in Eq 7

### ISSUE THREAD

**Issue by valencebond** [wutong16/DistributionBalancedLoss#1]
in Eq7,  the for positive samples, zik in exponent should be -zik，and for negative samples，-λ *zik should be λ *zik, which is  consistent with formulation in Eq5.

please correct me if there is something wrong. thanks~

**Comment by wutong16** [comment]
Thanks very much for pointing out the error!
You're right, and we sincerely apologize for our negligence... 
The code implementation is based on the right formulation, and we'll update the paper on Arxiv asap. to fix the symbol problem in Eq.(7) and Eq.(10)!
