### ISSUE TITLE
大佬，这个方法可以用在one stage模型中吗（yolov5）

### ISSUE THREAD

**Issue by CangHaiQingYue** [wutong16/DistributionBalancedLoss#12]
如题，谢谢~

**Comment by wutong16** [comment]
你好！抱歉回复迟了...我们没有在 detection 模型中应用过，也许可以尝试下~
不过 detection pipeline 比 classification 复杂得多，loss 除了分类外也还有 objectness 和 regression，配合起来不确定结果如何；而且第一部分的 R-BCE 要和 re-sampling 策略一起使用，也许会带来额外影响；不过副标签抑制那一部分我觉的可以单独拿出来试试，因为它想解决的是分类和检测都有的正负标签不均问题~

**Comment by CangHaiQingYue** [comment]
谢谢回复！
