### ISSUE TITLE
Reproduction of Distribution-Balanced Loss on VOC Dataset

### ISSUE THREAD

**Issue by limengyang1992** [wutong16/DistributionBalancedLoss#15]
Distribution-Balanced Loss is a very good work, we reproduced the experimental results in coco long tail experiment, but the difference of mAP on VOC dataset is almost 1 point, is there something wrong with our settings, looking forward to your reply~
![feab3d95c0ad8b8c89e46613266a741](https://user-images.githubusercontent.com/73928007/178926317-28edf774-a861-466e-acfc-2249baf51da8.png)

**Comment by wutong16** [comment]
Hi @limengyang1992 ！

Thanks for your attention to our work. The issue is probably caused by the sensitivity to the randomness because of the small data scale. Please try another random seed, e.g. `--seed 1`, which produces a total mAP of around 79.0 here on my server.

**Comment by limengyang1992** [comment]
It solved my problem, thank you very much for your reply

**Comment by limengyang1992** [comment]
> Hi @limengyang1992 ！
> 
> Thanks for your attention to our work. The issue is probably caused by the sensitivity to the randomness because of the small data scale. Please try another random seed, e.g. `--seed 1`, which produces a total mAP of around 79.0 here on my server.

It solved my problem, thank you very much for your reply
