### ISSUE TITLE
About Class aware sampler

### ISSUE THREAD

**Issue by zhandand** [wutong16/DistributionBalancedLoss#17]
https://github.com/wutong16/DistributionBalancedLoss/blob/14460d0acda6a3e77a8a6a5999b9746243cb1535/mllt/datasets/loader/sampler.py#L255
I wonder why this lined was commented and introduce the variance "num_samples_cls". In my opion, this line can accomplish the same function as the lines below, is that right? Or could you please tell why use variance "num_samples_cls", was that for code efficiency？
Thanks a lot!

**Comment by wutong16** [comment]
Hi! We adopt the implementation of the class-aware sampler by OLTR [here](https://github.com/zhmiao/OpenLongTailRecognition-OLTR/blob/master/data/ClassAwareSampler.py#L31).

**Comment by zhandand** [comment]
Thanks for your code link. I have found the meaning of that variance [here](https://github.com/zhmiao/OpenLongTailRecognition-OLTR/issues/34#issue-485010073)
