### ISSUE TITLE
ModuleNotFoundError: No module named 'lvis'

### ISSUE THREAD

**Issue by taomrzhang** [wutong16/DistributionBalancedLoss#5]
Traceback (most recent call last):
  File "tools/train.py", line 11, in <module>
    from mllt.datasets import build_dataset
  File "/content/drive/My Drive/DistributionBalancedLoss/mllt/datasets/__init__.py", line 4, in <module>
    from .Lvis import LvisDataset
  File "/content/drive/My Drive/DistributionBalancedLoss/mllt/datasets/Lvis.py", line 2, in <module>
    from lvis.lvis import LVIS
ModuleNotFoundError: No module named 'lvis'
when I run python tools/train.py configs/coco/LT_resnet50_pfc_DB.py , this erorr is rasied. I think a lvis file should be existed, however, i can't find it. can you tell how to solve this erorr? thank you!

**Comment by taomrzhang** [comment]
i have been solved.
please refer to this link: 'https://github.com/lvis-dataset/lvis-api'

**Comment by AfiqHamdani** [comment]
Hi, nice to meet you. Sorry for bothering but I have the same error as this. After I downloaded the lvis-api at the link given, where should I put it inside the models folder? Is it `models>research>object_detection`? Or somewhere else? Thank you
