### ISSUE TITLE
About the formula(9) is inconstense with the code implementation.

### ISSUE THREAD

**Issue by mingliangzhang2018** [wutong16/DistributionBalancedLoss#8]
Thanks for your excited work. I'm wondering why the code implementation is inconstense with the formula(9).
![image](https://user-images.githubusercontent.com/38106776/104688637-0ba5c680-573c-11eb-9e16-21bd8b59f658.png)
![image](https://user-images.githubusercontent.com/38106776/104688685-211af080-573c-11eb-8e4c-71c6abd0c9e1.png)

**Comment by wutong16** [comment]
Hi @ZMLLLL, sorry for the late reply!

We checked the code and find that `/ self.neg_scale` is indeed not supposed to be here, leading to the hyper-parameter \kappa being \lambda (2~5) times smaller. We're sorry for the inconsistency and thank you for kindly pointing it out! 
The bug only changes the choice of the hyper-paramter `init_bias` (\kappa, default as 0.05) and does not influence the main idea of the paper. 

Thanks again for your attention to our work.
